// Package devicecontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package devicecontract

const (
	DeviceSignatureScopes = "DeviceSignature.Scopes"
)

// Defines values for ChallengeRequestMethod.
const (
	GET  ChallengeRequestMethod = "GET"
	POST ChallengeRequestMethod = "POST"
)

// Defines values for ChallengeRequestPurpose.
const (
	ChallengeRequestPurposeActivate          ChallengeRequestPurpose = "activate"
	ChallengeRequestPurposeCommandApply      ChallengeRequestPurpose = "command.apply"
	ChallengeRequestPurposeCommandDisable    ChallengeRequestPurpose = "command.disable"
	ChallengeRequestPurposeCommandRevoke     ChallengeRequestPurpose = "command.revoke"
	ChallengeRequestPurposeCredentialReceipt ChallengeRequestPurpose = "credential.receipt"
	ChallengeRequestPurposeCredentialRotate  ChallengeRequestPurpose = "credential.rotate"
	ChallengeRequestPurposeOperationReceipt  ChallengeRequestPurpose = "operation.receipt"
	ChallengeRequestPurposeOperationStatus   ChallengeRequestPurpose = "operation.status"
	ChallengeRequestPurposeProxyBootstrap    ChallengeRequestPurpose = "proxy.bootstrap"
	ChallengeRequestPurposeRequestResolve    ChallengeRequestPurpose = "request.resolve"
)

// Defines values for ChallengeRequestReceiptKind.
const (
	ChallengeRequestReceiptKindActivate         ChallengeRequestReceiptKind = "activate"
	ChallengeRequestReceiptKindCommandApply     ChallengeRequestReceiptKind = "command.apply"
	ChallengeRequestReceiptKindCommandDisable   ChallengeRequestReceiptKind = "command.disable"
	ChallengeRequestReceiptKindCommandRevoke    ChallengeRequestReceiptKind = "command.revoke"
	ChallengeRequestReceiptKindCredentialRotate ChallengeRequestReceiptKind = "credential.rotate"
)

// Defines values for CommandAction.
const (
	Apply   CommandAction = "apply"
	Disable CommandAction = "disable"
	Revoke  CommandAction = "revoke"
)

// Defines values for CredentialReceiptRequestKind.
const (
	CredentialReceiptRequestKindActivate         CredentialReceiptRequestKind = "activate"
	CredentialReceiptRequestKindCredentialRotate CredentialReceiptRequestKind = "credential.rotate"
)

// Defines values for ErrorCode.
const (
	Conflict       ErrorCode = "conflict"
	InvalidRequest ErrorCode = "invalid_request"
	NotFound       ErrorCode = "not_found"
	RateLimited    ErrorCode = "rate_limited"
	Unauthorized   ErrorCode = "unauthorized"
	Unavailable    ErrorCode = "unavailable"
)

// Defines values for OperationState.
const (
	Degraded   OperationState = "degraded"
	Done       OperationState = "done"
	Pending    OperationState = "pending"
	Superseded OperationState = "superseded"
)

// Defines values for ProxyBootstrapVersion.
const (
	ProxyBootstrapVersionN1 ProxyBootstrapVersion = 1
)

// Defines values for ProxyRouteProfileVersion.
const (
	ProxyRouteProfileVersionN1 ProxyRouteProfileVersion = 1
)

// Defines values for ResolveReceiptKind.
const (
	ResolveReceiptKindActivate         ResolveReceiptKind = "activate"
	ResolveReceiptKindCommandApply     ResolveReceiptKind = "command.apply"
	ResolveReceiptKindCommandDisable   ResolveReceiptKind = "command.disable"
	ResolveReceiptKindCommandRevoke    ResolveReceiptKind = "command.revoke"
	ResolveReceiptKindCredentialRotate ResolveReceiptKind = "credential.rotate"
)

// Defines values for ResolveReceiptState.
const (
	Cancelled ResolveReceiptState = "cancelled"
	Committed ResolveReceiptState = "committed"
)

// Defines values for ResolveRequestKind.
const (
	Activate         ResolveRequestKind = "activate"
	CommandApply     ResolveRequestKind = "command.apply"
	CommandDisable   ResolveRequestKind = "command.disable"
	CommandRevoke    ResolveRequestKind = "command.revoke"
	CredentialRotate ResolveRequestKind = "credential.rotate"
)

// ActivationRequest defines model for ActivationRequest.
type ActivationRequest struct {
	ActivationCredential string `json:"activation_credential"`
	AuthPublicKey        string `json:"auth_public_key"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	ChallengeId        string `json:"challenge_id"`
	ExpiresUnixSeconds int64  `json:"expires_unix_seconds"`
	Nonce              string `json:"nonce"`
}

// ChallengeRequest defines model for ChallengeRequest.
type ChallengeRequest struct {
	ActivationCredential  *string                      `json:"activation_credential,omitempty"`
	AuthPublicKey         *string                      `json:"auth_public_key,omitempty"`
	BodySha256            string                       `json:"body_sha256"`
	CredentialId          *string                      `json:"credential_id,omitempty"`
	DeviceId              *string                      `json:"device_id,omitempty"`
	Method                ChallengeRequestMethod       `json:"method"`
	Path                  string                       `json:"path"`
	Purpose               ChallengeRequestPurpose      `json:"purpose"`
	ReceiptIdempotencyKey *string                      `json:"receipt_idempotency_key,omitempty"`
	ReceiptKind           *ChallengeRequestReceiptKind `json:"receipt_kind,omitempty"`
	ReceiptRequestId      *string                      `json:"receipt_request_id,omitempty"`
}

// ChallengeRequestMethod defines model for ChallengeRequest.Method.
type ChallengeRequestMethod string

// ChallengeRequestPurpose defines model for ChallengeRequest.Purpose.
type ChallengeRequestPurpose string

// ChallengeRequestReceiptKind defines model for ChallengeRequest.ReceiptKind.
type ChallengeRequestReceiptKind string

// Command defines model for Command.
type Command struct {
	Action             CommandAction `json:"action"`
	Address            *string       `json:"address,omitempty"`
	ExpectedGeneration int64         `json:"expected_generation"`
	IdempotencyKey     string        `json:"idempotency_key"`
	Reason             *string       `json:"reason,omitempty"`
	WgPublicKey        *string       `json:"wg_public_key,omitempty"`
}

// CommandAction defines model for Command.Action.
type CommandAction string

// Credential defines model for Credential.
type Credential struct {
	AuthPublicKey      string `json:"auth_public_key"`
	CredentialId       string `json:"credential_id"`
	DeviceId           string `json:"device_id"`
	ExpiresUnixSeconds int64  `json:"expires_unix_seconds"`
}

// CredentialReceiptRequest defines model for CredentialReceiptRequest.
type CredentialReceiptRequest struct {
	AuthPublicKey string                       `json:"auth_public_key"`
	Kind          CredentialReceiptRequestKind `json:"kind"`
	RequestId     string                       `json:"request_id"`
}

// CredentialReceiptRequestKind defines model for CredentialReceiptRequest.Kind.
type CredentialReceiptRequestKind string

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Operation defines model for Operation.
type Operation struct {
	Accepted            bool           `json:"accepted"`
	Action              string         `json:"action"`
	DeadlineUnixSeconds int64          `json:"deadline_unix_seconds"`
	DeviceId            string         `json:"device_id"`
	Effective           bool           `json:"effective"`
	Generation          int64          `json:"generation"`
	LastError           string         `json:"last_error"`
	OperationId         string         `json:"operation_id"`
	State               OperationState `json:"state"`
}

// OperationState defines model for Operation.State.
type OperationState string

// OperationReceiptRequest defines model for OperationReceiptRequest.
type OperationReceiptRequest struct {
	IdempotencyKey string `json:"idempotency_key"`
	RequestId      string `json:"request_id"`
}

// ProxyBootstrap defines model for ProxyBootstrap.
type ProxyBootstrap struct {
	// Address Current canonical private customer IPv4 host /32
	Address            string `json:"address"`
	AppliedGeneration  int64  `json:"applied_generation"`
	CredentialId       string `json:"credential_id"`
	DesiredGeneration  int64  `json:"desired_generation"`
	DeviceId           string `json:"device_id"`
	ExpiresUnixSeconds int64  `json:"expires_unix_seconds"`
	IssuedUnixSeconds  int64  `json:"issued_unix_seconds"`

	// Profile Operator-maintained immutable service-lifetime profile, not caller input. Version 1 permits exactly one canonical private IPv4 proxy /32, excludes legacy management 10.66.0.0/24 and default routes. The endpoint is a canonical IPv4 host and decimal port; no DNS lookup or endpoint probing is performed by validation. Canonical digest is SHA256 of UTF-8 json.Marshal of the ordered string array [zhvpn-device-route,v1,decimal version,authority_epoch,managed_by,wg_interface,decimal revision,wg_endpoint,wg_public_key,proxy_address,egress_id,egress_name,sole allowed_ips entry]. Strings have their exact validated bytes; standard Go JSON escaping is part of this versioned digest contract. This digest detects content identity, not an offline signature or filesystem antirollback.
	Profile            ProxyRouteProfile     `json:"profile"`
	ProfileSha256      string                `json:"profile_sha256"`
	Version            ProxyBootstrapVersion `json:"version"`
	WireguardPublicKey string                `json:"wireguard_public_key"`
}

// ProxyBootstrapVersion defines model for ProxyBootstrap.Version.
type ProxyBootstrapVersion int64

// ProxyBootstrapRequest defines model for ProxyBootstrapRequest.
type ProxyBootstrapRequest struct {
	ExpectedGeneration int64  `json:"expected_generation"`
	WireguardPublicKey string `json:"wireguard_public_key"`
}

// ProxyRouteProfile Operator-maintained immutable service-lifetime profile, not caller input. Version 1 permits exactly one canonical private IPv4 proxy /32, excludes legacy management 10.66.0.0/24 and default routes. The endpoint is a canonical IPv4 host and decimal port; no DNS lookup or endpoint probing is performed by validation. Canonical digest is SHA256 of UTF-8 json.Marshal of the ordered string array [zhvpn-device-route,v1,decimal version,authority_epoch,managed_by,wg_interface,decimal revision,wg_endpoint,wg_public_key,proxy_address,egress_id,egress_name,sole allowed_ips entry]. Strings have their exact validated bytes; standard Go JSON escaping is part of this versioned digest contract. This digest detects content identity, not an offline signature or filesystem antirollback.
type ProxyRouteProfile struct {
	AllowedIps     []string                 `json:"allowed_ips"`
	AuthorityEpoch string                   `json:"authority_epoch"`
	EgressId       string                   `json:"egress_id"`
	EgressName     string                   `json:"egress_name"`
	ManagedBy      string                   `json:"managed_by"`
	ProxyAddress   string                   `json:"proxy_address"`
	Revision       int64                    `json:"revision"`
	Version        ProxyRouteProfileVersion `json:"version"`
	WgEndpoint     string                   `json:"wg_endpoint"`
	WgInterface    string                   `json:"wg_interface"`
	WgPublicKey    string                   `json:"wg_public_key"`
}

// ProxyRouteProfileVersion defines model for ProxyRouteProfile.Version.
type ProxyRouteProfileVersion int64

// ResolveReceipt defines model for ResolveReceipt.
type ResolveReceipt struct {
	AuthPublicKey  *string             `json:"auth_public_key,omitempty"`
	Credential     *Credential         `json:"credential,omitempty"`
	IdempotencyKey *string             `json:"idempotency_key,omitempty"`
	Kind           ResolveReceiptKind  `json:"kind"`
	Operation      *Operation          `json:"operation,omitempty"`
	RequestId      string              `json:"request_id"`
	State          ResolveReceiptState `json:"state"`
}

// ResolveReceiptKind defines model for ResolveReceipt.Kind.
type ResolveReceiptKind string

// ResolveReceiptState defines model for ResolveReceipt.State.
type ResolveReceiptState string

// ResolveRequest defines model for ResolveRequest.
type ResolveRequest struct {
	ActivationCredential *string            `json:"activation_credential,omitempty"`
	AuthPublicKey        *string            `json:"auth_public_key,omitempty"`
	IdempotencyKey       *string            `json:"idempotency_key,omitempty"`
	Kind                 ResolveRequestKind `json:"kind"`
	RequestId            string             `json:"request_id"`
}

// ResolveRequestKind defines model for ResolveRequest.Kind.
type ResolveRequestKind string

// RotationRequest defines model for RotationRequest.
type RotationRequest struct {
	AuthPublicKey string `json:"auth_public_key"`
}

// ChallengeId defines model for ChallengeId.
type ChallengeId = string

// CredentialId defines model for CredentialId.
type CredentialId = string

// DeviceId defines model for DeviceId.
type DeviceId = string

// Expires defines model for Expires.
type Expires = int64

// Nonce defines model for Nonce.
type Nonce = string

// RequestId defines model for RequestId.
type RequestId = string

// Signature defines model for Signature.
type Signature = string

// ActivateDeviceParams defines parameters for ActivateDevice.
type ActivateDeviceParams struct {
	XZHChallenge ChallengeId `json:"X-ZH-Challenge"`
	XZHNonce     Nonce       `json:"X-ZH-Nonce"`
	XZHExpires   Expires     `json:"X-ZH-Expires"`
	XZHRequestID RequestId   `json:"X-ZH-Request-ID"`
	XZHSignature Signature   `json:"X-ZH-Signature"`
}

// CreateChallengeParams defines parameters for CreateChallenge.
type CreateChallengeParams struct {
	XZHChallengeProof string `json:"X-ZH-Challenge-Proof"`
	XZHClientNonce    string `json:"X-ZH-Client-Nonce"`
	XZHClientExpires  int64  `json:"X-ZH-Client-Expires"`

	// XZHResolveOwnerProof Required only for request.resolve credential.rotate. Original credential key signs the identical challenge proof bytes; primary challenge proof uses the proposed new key.
	XZHResolveOwnerProof *string `json:"X-ZH-Resolve-Owner-Proof,omitempty"`
}

// SubmitCommandParams defines parameters for SubmitCommand.
type SubmitCommandParams struct {
	XZHDevice     DeviceId     `json:"X-ZH-Device"`
	XZHCredential CredentialId `json:"X-ZH-Credential"`
	XZHChallenge  ChallengeId  `json:"X-ZH-Challenge"`
	XZHNonce      Nonce        `json:"X-ZH-Nonce"`
	XZHExpires    Expires      `json:"X-ZH-Expires"`
	XZHRequestID  RequestId    `json:"X-ZH-Request-ID"`
	XZHSignature  Signature    `json:"X-ZH-Signature"`
}

// GetCredentialReceiptParams defines parameters for GetCredentialReceipt.
type GetCredentialReceiptParams struct {
	XZHChallenge ChallengeId `json:"X-ZH-Challenge"`
	XZHNonce     Nonce       `json:"X-ZH-Nonce"`
	XZHExpires   Expires     `json:"X-ZH-Expires"`
	XZHRequestID RequestId   `json:"X-ZH-Request-ID"`
	XZHSignature Signature   `json:"X-ZH-Signature"`
}

// RotateCredentialParams defines parameters for RotateCredential.
type RotateCredentialParams struct {
	XZHDevice          DeviceId     `json:"X-ZH-Device"`
	XZHCredential      CredentialId `json:"X-ZH-Credential"`
	XZHChallenge       ChallengeId  `json:"X-ZH-Challenge"`
	XZHNonce           Nonce        `json:"X-ZH-Nonce"`
	XZHExpires         Expires      `json:"X-ZH-Expires"`
	XZHRequestID       RequestId    `json:"X-ZH-Request-ID"`
	XZHSignature       Signature    `json:"X-ZH-Signature"`
	XZHNewKeySignature string       `json:"X-ZH-New-Key-Signature"`
}

// GetOperationReceiptParams defines parameters for GetOperationReceipt.
type GetOperationReceiptParams struct {
	XZHDevice     DeviceId     `json:"X-ZH-Device"`
	XZHCredential CredentialId `json:"X-ZH-Credential"`
	XZHChallenge  ChallengeId  `json:"X-ZH-Challenge"`
	XZHNonce      Nonce        `json:"X-ZH-Nonce"`
	XZHExpires    Expires      `json:"X-ZH-Expires"`
	XZHRequestID  RequestId    `json:"X-ZH-Request-ID"`
	XZHSignature  Signature    `json:"X-ZH-Signature"`
}

// GetOperationParams defines parameters for GetOperation.
type GetOperationParams struct {
	XZHDevice     DeviceId     `json:"X-ZH-Device"`
	XZHCredential CredentialId `json:"X-ZH-Credential"`
	XZHChallenge  ChallengeId  `json:"X-ZH-Challenge"`
	XZHNonce      Nonce        `json:"X-ZH-Nonce"`
	XZHExpires    Expires      `json:"X-ZH-Expires"`
	XZHRequestID  RequestId    `json:"X-ZH-Request-ID"`
	XZHSignature  Signature    `json:"X-ZH-Signature"`
}

// BootstrapProxyParams defines parameters for BootstrapProxy.
type BootstrapProxyParams struct {
	XZHDevice     DeviceId     `json:"X-ZH-Device"`
	XZHCredential CredentialId `json:"X-ZH-Credential"`
	XZHChallenge  ChallengeId  `json:"X-ZH-Challenge"`
	XZHNonce      Nonce        `json:"X-ZH-Nonce"`
	XZHExpires    Expires      `json:"X-ZH-Expires"`
	XZHRequestID  RequestId    `json:"X-ZH-Request-ID"`
	XZHSignature  Signature    `json:"X-ZH-Signature"`
}

// ResolvePendingRequestParams defines parameters for ResolvePendingRequest.
type ResolvePendingRequestParams struct {
	XZHChallenge ChallengeId `json:"X-ZH-Challenge"`
	XZHNonce     Nonce       `json:"X-ZH-Nonce"`
	XZHExpires   Expires     `json:"X-ZH-Expires"`
	XZHRequestID RequestId   `json:"X-ZH-Request-ID"`
	XZHSignature Signature   `json:"X-ZH-Signature"`

	// XZHDevice Required for rotation and commands; forbidden for activation.
	XZHDevice *string `json:"X-ZH-Device,omitempty"`

	// XZHCredential Required for rotation and commands; forbidden for activation.
	XZHCredential *string `json:"X-ZH-Credential,omitempty"`

	// XZHResolveOwnerProof Required only for rotation; original key signs identical signed-request bytes.
	XZHResolveOwnerProof *string `json:"X-ZH-Resolve-Owner-Proof,omitempty"`
}

// ActivateDeviceJSONRequestBody defines body for ActivateDevice for application/json ContentType.
type ActivateDeviceJSONRequestBody = ActivationRequest

// CreateChallengeJSONRequestBody defines body for CreateChallenge for application/json ContentType.
type CreateChallengeJSONRequestBody = ChallengeRequest

// SubmitCommandJSONRequestBody defines body for SubmitCommand for application/json ContentType.
type SubmitCommandJSONRequestBody = Command

// GetCredentialReceiptJSONRequestBody defines body for GetCredentialReceipt for application/json ContentType.
type GetCredentialReceiptJSONRequestBody = CredentialReceiptRequest

// RotateCredentialJSONRequestBody defines body for RotateCredential for application/json ContentType.
type RotateCredentialJSONRequestBody = RotationRequest

// GetOperationReceiptJSONRequestBody defines body for GetOperationReceipt for application/json ContentType.
type GetOperationReceiptJSONRequestBody = OperationReceiptRequest

// BootstrapProxyJSONRequestBody defines body for BootstrapProxy for application/json ContentType.
type BootstrapProxyJSONRequestBody = ProxyBootstrapRequest

// ResolvePendingRequestJSONRequestBody defines body for ResolvePendingRequest for application/json ContentType.
type ResolvePendingRequestJSONRequestBody = ResolveRequest
