// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package storage

import (
	"context"
	"database/sql"
)

const countAuditEventsSince = `-- name: CountAuditEventsSince :one
SELECT count(*)
FROM audit_events
WHERE event_type IN ('client.rotate_ip', 'admin.rotate_ip')
  AND result = 'ok'
  AND occurred_at >= ?
`

func (q *Queries) CountAuditEventsSince(ctx context.Context, occurredAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEventsSince, occurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedLoginAttempts = `-- name: CountRecentFailedLoginAttempts :one
SELECT count(*)
FROM admin_login_attempts
WHERE username = ?
  AND source_ip = ?
  AND success = 0
  AND occurred_at >= ?
`

type CountRecentFailedLoginAttemptsParams struct {
	Username   string `json:"username"`
	SourceIp   string `json:"source_ip"`
	OccurredAt string `json:"occurred_at"`
}

func (q *Queries) CountRecentFailedLoginAttempts(ctx context.Context, arg CountRecentFailedLoginAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttempts, arg.Username, arg.SourceIp, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO admin_sessions (
  id, username, token_hash, csrf_token, source_ip, user_agent,
  created_at, last_seen_at, expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAdminSessionParams struct {
	ID         string `json:"id"`
	Username   string `json:"username"`
	TokenHash  string `json:"token_hash"`
	CsrfToken  string `json:"csrf_token"`
	SourceIp   string `json:"source_ip"`
	UserAgent  string `json:"user_agent"`
	CreatedAt  string `json:"created_at"`
	LastSeenAt string `json:"last_seen_at"`
	ExpiresAt  string `json:"expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAdminSession,
		arg.ID,
		arg.Username,
		arg.TokenHash,
		arg.CsrfToken,
		arg.SourceIp,
		arg.UserAgent,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAdminSessionByHash = `-- name: DeleteAdminSessionByHash :exec
DELETE FROM admin_sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteAdminSessionByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAdminSessionByHash, tokenHash)
	return err
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAdminSessions, expiresAt)
	return err
}

const deleteExpiredTokenLeases = `-- name: DeleteExpiredTokenLeases :exec
DELETE FROM token_leases
WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) DeleteExpiredTokenLeases(ctx context.Context, expiresAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokenLeases, expiresAt)
	return err
}

const deleteRotateLock = `-- name: DeleteRotateLock :exec
DELETE FROM rotate_locks
WHERE egress_id = ?
`

func (q *Queries) DeleteRotateLock(ctx context.Context, egressID string) error {
	_, err := q.db.ExecContext(ctx, deleteRotateLock, egressID)
	return err
}

const getAdminSessionByHash = `-- name: GetAdminSessionByHash :one
SELECT id, username, token_hash, csrf_token, source_ip, user_agent,
       created_at, last_seen_at, expires_at
FROM admin_sessions
WHERE token_hash = ?
`

func (q *Queries) GetAdminSessionByHash(ctx context.Context, tokenHash string) (AdminSession, error) {
	row := q.db.QueryRowContext(ctx, getAdminSessionByHash, tokenHash)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TokenHash,
		&i.CsrfToken,
		&i.SourceIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT username, password_hash, created_at, updated_at
FROM admin_users
WHERE username = ?
`

func (q *Queries) GetAdminUser(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUser, username)
	var i AdminUser
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
  occurred_at, actor, source_ip, event_type, target, detail_json, result, error_code
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	OccurredAt string `json:"occurred_at"`
	Actor      string `json:"actor"`
	SourceIp   string `json:"source_ip"`
	EventType  string `json:"event_type"`
	Target     string `json:"target"`
	DetailJson string `json:"detail_json"`
	Result     string `json:"result"`
	ErrorCode  string `json:"error_code"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.OccurredAt,
		arg.Actor,
		arg.SourceIp,
		arg.EventType,
		arg.Target,
		arg.DetailJson,
		arg.Result,
		arg.ErrorCode,
	)
	return err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO admin_login_attempts (occurred_at, username, source_ip, success, error_code)
VALUES (?, ?, ?, ?, ?)
`

type InsertLoginAttemptParams struct {
	OccurredAt string `json:"occurred_at"`
	Username   string `json:"username"`
	SourceIp   string `json:"source_ip"`
	Success    int64  `json:"success"`
	ErrorCode  string `json:"error_code"`
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginAttempt,
		arg.OccurredAt,
		arg.Username,
		arg.SourceIp,
		arg.Success,
		arg.ErrorCode,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor, source_ip, event_type, target, detail_json, result, error_code
FROM audit_events
ORDER BY occurred_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListAuditEvents(ctx context.Context, limit int64) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.SourceIp,
			&i.EventType,
			&i.Target,
			&i.DetailJson,
			&i.Result,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAdminSession = `-- name: TouchAdminSession :exec
UPDATE admin_sessions
SET last_seen_at = ?
WHERE token_hash = ?
`

type TouchAdminSessionParams struct {
	LastSeenAt string `json:"last_seen_at"`
	TokenHash  string `json:"token_hash"`
}

func (q *Queries) TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchAdminSession, arg.LastSeenAt, arg.TokenHash)
	return err
}

const upsertAdminUser = `-- name: UpsertAdminUser :exec
INSERT INTO admin_users (username, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(username) DO UPDATE SET
  password_hash = excluded.password_hash,
  updated_at = excluded.updated_at
`

type UpsertAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertAdminUser,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertEgressNode = `-- name: UpsertEgressNode :exec
INSERT INTO egress_nodes (
  egress_id, display_name, region, type, management_addr, proxy_addr, deprecated, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(egress_id) DO UPDATE SET
  display_name = excluded.display_name,
  region = excluded.region,
  type = excluded.type,
  management_addr = excluded.management_addr,
  proxy_addr = excluded.proxy_addr,
  deprecated = excluded.deprecated,
  updated_at = excluded.updated_at
`

type UpsertEgressNodeParams struct {
	EgressID       string `json:"egress_id"`
	DisplayName    string `json:"display_name"`
	Region         string `json:"region"`
	Type           string `json:"type"`
	ManagementAddr string `json:"management_addr"`
	ProxyAddr      string `json:"proxy_addr"`
	Deprecated     int64  `json:"deprecated"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) UpsertEgressNode(ctx context.Context, arg UpsertEgressNodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEgressNode,
		arg.EgressID,
		arg.DisplayName,
		arg.Region,
		arg.Type,
		arg.ManagementAddr,
		arg.ProxyAddr,
		arg.Deprecated,
		arg.UpdatedAt,
	)
	return err
}

const upsertRotateLock = `-- name: UpsertRotateLock :exec
INSERT INTO rotate_locks (egress_id, started_at, until_at)
VALUES (?, ?, ?)
ON CONFLICT(egress_id) DO UPDATE SET
  started_at = excluded.started_at,
  until_at = excluded.until_at
`

type UpsertRotateLockParams struct {
	EgressID  string `json:"egress_id"`
	StartedAt string `json:"started_at"`
	UntilAt   string `json:"until_at"`
}

func (q *Queries) UpsertRotateLock(ctx context.Context, arg UpsertRotateLockParams) error {
	_, err := q.db.ExecContext(ctx, upsertRotateLock, arg.EgressID, arg.StartedAt, arg.UntilAt)
	return err
}

const upsertTokenCache = `-- name: UpsertTokenCache :exec
INSERT INTO tokens_cache (
  token, masked_token, client_name, enabled, expires_at,
  egress_id, egress_name, wg_address, last_sync_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(token) DO UPDATE SET
  masked_token = excluded.masked_token,
  client_name = excluded.client_name,
  enabled = excluded.enabled,
  expires_at = excluded.expires_at,
  egress_id = excluded.egress_id,
  egress_name = excluded.egress_name,
  wg_address = excluded.wg_address,
  last_sync_at = excluded.last_sync_at
`

type UpsertTokenCacheParams struct {
	Token       string         `json:"token"`
	MaskedToken string         `json:"masked_token"`
	ClientName  string         `json:"client_name"`
	Enabled     int64          `json:"enabled"`
	ExpiresAt   sql.NullString `json:"expires_at"`
	EgressID    string         `json:"egress_id"`
	EgressName  string         `json:"egress_name"`
	WgAddress   string         `json:"wg_address"`
	LastSyncAt  string         `json:"last_sync_at"`
}

func (q *Queries) UpsertTokenCache(ctx context.Context, arg UpsertTokenCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertTokenCache,
		arg.Token,
		arg.MaskedToken,
		arg.ClientName,
		arg.Enabled,
		arg.ExpiresAt,
		arg.EgressID,
		arg.EgressName,
		arg.WgAddress,
		arg.LastSyncAt,
	)
	return err
}

const upsertTokenLease = `-- name: UpsertTokenLease :exec
INSERT INTO token_leases (
  token, masked_token, client_name, source_ip, egress_id, seen_at, expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(token) DO UPDATE SET
  masked_token = excluded.masked_token,
  client_name = excluded.client_name,
  source_ip = excluded.source_ip,
  egress_id = excluded.egress_id,
  seen_at = excluded.seen_at,
  expires_at = excluded.expires_at
`

type UpsertTokenLeaseParams struct {
	Token       string         `json:"token"`
	MaskedToken string         `json:"masked_token"`
	ClientName  string         `json:"client_name"`
	SourceIp    string         `json:"source_ip"`
	EgressID    string         `json:"egress_id"`
	SeenAt      string         `json:"seen_at"`
	ExpiresAt   sql.NullString `json:"expires_at"`
}

func (q *Queries) UpsertTokenLease(ctx context.Context, arg UpsertTokenLeaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertTokenLease,
		arg.Token,
		arg.MaskedToken,
		arg.ClientName,
		arg.SourceIp,
		arg.EgressID,
		arg.SeenAt,
		arg.ExpiresAt,
	)
	return err
}
