"""Embed fixed read-only validation programs; paths arrive only via environment."""
import argparse
import base64
from pathlib import Path

root = Path(__file__).resolve().parent
lines = ['; Generated by installer-guardgen.py; do not edit.']
for name in ('parent', 'payload'):
    program = (root / f'installer-{name}-guard.ps1').read_text(encoding='utf-8').replace('\r\n', '\n')
    encoded = base64.b64encode(program.encode('utf-16-le')).decode('ascii')
    chunks = [encoded[offset:offset + 640] for offset in range(0, len(encoded), 640)]
    if len(chunks) > 32:
        raise SystemExit(f'{name} validation exceeds the embedded program budget')
    # Tauri distributes NSIS with 1024-character runtime strings. Programs are
    # carried in fixed process environment chunks; a short embedded bootstrap
    # reconstructs them. No writable temporary script is executed.
    prefix = f'ZHVPN_{name.upper()}_PROGRAM_'
    bootstrap = f"$b=(0..{len(chunks)-1}|%{{[Environment]::GetEnvironmentVariable('{prefix}'+$_)}})-join ''; & ([ScriptBlock]::Create([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($b))))"
    command = base64.b64encode(bootstrap.encode('utf-16-le')).decode('ascii')
    if len(command) > 850:
        raise SystemExit('bootstrap exceeds the NSIS command budget')
    lines.append(f'!define ZHVPN_{name.upper()}_VALIDATOR "{command}"')
    lines.append(f'!macro ZHVPN_SET_{name.upper()}_PROGRAM')
    for index, chunk in enumerate(chunks):
        lines.append(f"  System::Call 'kernel32::SetEnvironmentVariableW(w \"{prefix}{index}\", w \"{chunk}\")'")
    lines.append('!macroend')
data = '\n'.join(lines) + '\n'
output = root.parent / 'src-tauri' / 'installer-validation.generated.nsh'
parser = argparse.ArgumentParser()
parser.add_argument('-check', action='store_true')
args = parser.parse_args()
if args.check:
    if not output.exists() or output.read_text(encoding='utf-8') != data:
        raise SystemExit('installer validation program is stale; run installer-guardgen.py')
else:
    output.write_text(data, encoding='utf-8', newline='\n')
