// Code generated by shared/contracts/cmd/contractgen; DO NOT EDIT.
package contracts

// Status is the public v1 CLI DTO.
type Status struct {
	Running                bool   `json:"running"`
	Proxy                  string `json:"proxy,omitempty"`
	ProxyReachable         bool   `json:"proxy_reachable"`
	Egress                 string `json:"egress,omitempty"`
	EgressIP               string `json:"egress_ip,omitempty"`
	EgressIPv4             string `json:"egress_ipv4,omitempty"`
	EgressIPv6             string `json:"egress_ipv6,omitempty"`
	Error                  string `json:"error,omitempty"`
	ErrorCode              string `json:"error_code,omitempty"`
	EngineState            string `json:"engine_state"`
	InstanceID             string `json:"instance_id,omitempty"`
	ConfigGeneration       string `json:"config_generation,omitempty"`
	ControlProtocolVersion int    `json:"control_protocol_version,omitempty"`
	PortOccupied           bool   `json:"port_occupied,omitempty"`
	ContractVersion        int    `json:"contract_version,omitempty"`
}

// Result is the public v1 CLI DTO.
type Result struct {
	OK              bool   `json:"ok"`
	Status          string `json:"status,omitempty"`
	Egress          string `json:"egress,omitempty"`
	Proxy           string `json:"proxy,omitempty"`
	Before          string `json:"before,omitempty"`
	After           string `json:"after,omitempty"`
	Message         string `json:"message,omitempty"`
	Product         string `json:"product,omitempty"`
	Version         string `json:"version,omitempty"`
	ProtocolVersion int    `json:"protocol_version,omitempty"`
	Error           string `json:"error,omitempty"`
	ErrorCode       string `json:"error_code,omitempty"`
	ContractVersion int    `json:"contract_version,omitempty"`
}

// EngineIdentity is the public v1 CLI DTO.
type EngineIdentity struct {
	InstanceID      string `json:"instance_id"`
	Home            string `json:"home"`
	Generation      string `json:"config_generation"`
	ProtocolVersion int    `json:"control_protocol_version"`
	PID             int    `json:"pid"`
}
