package contracts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// GeneratedFiles renders every public projection deterministically. There is
// no timestamp or environment-dependent output.
func GeneratedFiles() (map[string][]byte, error) {
	var dto bytes.Buffer
	dto.WriteString("// Code generated by shared/contracts/cmd/contractgen; DO NOT EDIT.\npackage contracts\n\n")
	for _, definition := range definitions() {
		fmt.Fprintf(&dto, "// %s is the public v%d CLI DTO.\ntype %s struct {\n", definition.Name, ContractVersion, definition.Name)
		for _, field := range definition.Fields {
			tag := field.JSONName
			if field.OmitEmpty {
				tag += ",omitempty"
			}
			fmt.Fprintf(&dto, "\t%s %s `json:%s`\n", field.GoName, field.GoType, strconv.Quote(tag))
		}
		dto.WriteString("}\n\n")
	}
	goData, err := format.Source(dto.Bytes())
	if err != nil {
		return nil, err
	}
	schema, err := json.MarshalIndent(Schema(), "", "  ")
	if err != nil {
		return nil, err
	}
	definitionsData, err := json.MarshalIndent(schemaDefinitions(), "", "  ")
	if err != nil {
		return nil, err
	}
	semantics, err := json.MarshalIndent(evidenceSemantics(), "", "  ")
	if err != nil {
		return nil, err
	}
	python := fmt.Sprintf("# Code generated by shared/contracts/cmd/contractgen; DO NOT EDIT.\nimport json\nfrom typing import Literal, TypedDict\n\nCONTRACT_VERSION = %d\nCONTROL_PROTOCOL_VERSION = %d\nSCHEMA_ID = %s\nDEFINITIONS = json.loads(%s)\nEVIDENCE_SEMANTICS = json.loads(%s)\nPRIVATE_FIELD_NAMES = %s\n", ContractVersion, ControlProtocolVersion, strconv.Quote(SchemaID), strconv.Quote(string(definitionsData)), strconv.Quote(string(semantics)), pythonStrings(privateFieldNames))
	var pythonDTO, typescript bytes.Buffer
	typescript.WriteString("// Code generated by shared/contracts/cmd/contractgen; DO NOT EDIT.\n")
	fmt.Fprintf(&typescript, "export const CONTRACT_VERSION = %d as const;\nexport const CONTROL_PROTOCOL_VERSION = %d as const;\n\n", ContractVersion, ControlProtocolVersion)
	for _, definition := range definitions() {
		fmt.Fprintf(&pythonDTO, "\n\nclass _%sRequired(TypedDict):\n", definition.Name)
		fmt.Fprintf(&typescript, "export interface %sDTO {\n", definition.Name)
		for _, field := range definition.Fields {
			pyType, tsType := publicFieldTypes(field)
			if field.Required {
				fmt.Fprintf(&pythonDTO, "    %s: %s\n", field.JSONName, pyType)
			}
			optional := "?"
			if field.Required {
				optional = ""
			}
			fmt.Fprintf(&typescript, "  %s%s: %s;\n", field.JSONName, optional, tsType)
		}
		fmt.Fprintf(&pythonDTO, "\n\nclass %sDTO(_%sRequired, total=False):\n", definition.Name, definition.Name)
		optionalCount := 0
		for _, field := range definition.Fields {
			if !field.Required {
				pyType, _ := publicFieldTypes(field)
				fmt.Fprintf(&pythonDTO, "    %s: %s\n", field.JSONName, pyType)
				optionalCount++
			}
		}
		if optionalCount == 0 {
			pythonDTO.WriteString("    pass\n")
		}
		typescript.WriteString("}\n\n")
	}
	python += pythonDTO.String()
	typescriptData := append(bytes.TrimRight(typescript.Bytes(), "\n"), '\n')
	return map[string][]byte{
		"shared/contracts/cli_v1_generated.go":               goData,
		"shared/contracts/cli-v1.schema.json":                append(schema, '\n'),
		"shared/contracts/cli_v1_generated.ts":               typescriptData,
		"clients/desktop-gui/src/lib/contracts.generated.ts": typescriptData,
		"sdk/python/src/zongheng_vpn/_contract_generated.py": []byte(python),
	}, nil
}

func publicFieldTypes(field fieldSpec) (string, string) {
	pyType := map[string]string{"string": "str", "int": "int", "bool": "bool"}[field.GoType]
	tsType := map[string]string{"string": "string", "int": "number", "bool": "boolean"}[field.GoType]
	if constant, ok := field.Constraints["const"]; ok {
		encoded, _ := json.Marshal(constant)
		pyType = "Literal[" + string(encoded) + "]"
		tsType = string(encoded)
	} else if enum, ok := field.Constraints["enum"].([]string); ok {
		values := make([]string, len(enum))
		for i, value := range enum {
			values[i] = strconv.Quote(value)
		}
		pyType = "Literal[" + strings.Join(values, ", ") + "]"
		tsType = strings.Join(values, " | ")
	}
	return pyType, tsType
}

func pythonStrings(values []string) string {
	data, _ := json.Marshal(values)
	return string(data)
}

// Generate writes projections, or verifies them byte-for-byte in check mode.
func Generate(root string, check bool) error {
	files, err := GeneratedFiles()
	if err != nil {
		return err
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(root, filepath.FromSlash(name))
		if check {
			actual, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(actual, files[name]) {
				return fmt.Errorf("generated contract drift: %s; run go generate ./shared/contracts", name)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(path, files[name], 0644); err != nil {
			return err
		}
	}
	return nil
}
