/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{token_id}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["revealTokenSecret"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLeases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egress/{egress_id}/exit-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["revealEgressExitIP"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egress/{egress_id}/rotate-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateEgressIP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthMeResponse: {
            username: string;
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ErrorResponse: {
            error: string;
            message?: string;
        };
        OverviewResponse: {
            hub: components["schemas"]["HubInfo"];
            stats: components["schemas"]["OverviewStats"];
            /** Format: date-time */
            updated_at: string;
        };
        HubInfo: {
            public_ip: string;
            wg_ip: string;
            version: string;
            /** Format: int64 */
            uptime_seconds: number;
        };
        OverviewStats: {
            token_count: number;
            enabled_token_count: number;
            active_lease_count: number;
            egress_online_count: number;
            rotate_today_count: number;
        };
        TokensResponse: {
            tokens: components["schemas"]["TokenSummary"][];
        };
        TokenSummary: {
            id: string;
            masked_token: string;
            client_name: string;
            enabled: boolean;
            /** @enum {string} */
            status: "enabled" | "disabled" | "expiring" | "expired";
            egress_id: string;
            egress_name: string;
            wg_address: string;
            expires_at: string | null;
            /** Format: date-time */
            last_active_at: string | null;
        };
        TokenSecretResponse: {
            id: string;
            token: string;
        };
        LeasesResponse: {
            leases: components["schemas"]["LeaseSummary"][];
        };
        LeaseSummary: {
            token_id: string;
            masked_token: string;
            client_name: string;
            source_ip: string;
            egress_id: string;
            /** Format: date-time */
            seen_at: string;
            /** Format: date-time */
            expires_at: string | null;
        };
        EgressResponse: {
            egress: components["schemas"]["EgressSummary"][];
        };
        EgressSummary: {
            id: string;
            display_name: string;
            region: string;
            type: string;
            management_addr: string;
            proxy_addr: string;
            /** @enum {string} */
            status: "online" | "degraded" | "offline" | "deprecated";
            session_count?: number;
            active_connections?: number;
            /** Format: date-time */
            rotate_lock_until?: string | null;
            raw_health?: {
                [key: string]: unknown;
            } | null;
        };
        EgressExitIPResponse: {
            egress_id: string;
            exit_ip: string;
            ipv4?: string;
            ipv6?: string;
            /** Format: date-time */
            checked_at: string;
        };
        EventsResponse: {
            events: components["schemas"]["AuditEvent"][];
        };
        AuditEvent: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            occurred_at: string;
            actor: string;
            source_ip: string;
            event_type: string;
            target: string;
            detail?: {
                [key: string]: unknown;
            } | null;
            result: string;
            error_code?: string | null;
        };
        RotateIPRequest: {
            /** @default 8 */
            down_seconds: number;
        };
        RotateIPResponse: {
            /** @enum {string} */
            status: "triggered" | "busy";
            egress_id: string;
            down_seconds: number;
            retry_after_seconds?: number;
            message?: string;
        };
    };
    responses: {
        /** @description JSON error response. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current admin session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getAdminHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin service health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hub overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    revealTokenSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revealed token value for an authenticated admin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSecretResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listLeases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active token leases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeasesResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listEgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Egress node status list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    revealEgressExitIP: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                egress_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current public exit IP measured through the egress proxy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressExitIPResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    rotateEgressIP: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                egress_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateIPRequest"];
            };
        };
        responses: {
            /** @description Rotate request dispatched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateIPResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            /** @description Egress is already rotating. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateIPResponse"];
                };
            };
        };
    };
}
