/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/migration/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMigrationReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{token_id}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["revealTokenSecret"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLeases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egress/{egress_id}/exit-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["revealEgressExitIP"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egress/{egress_id}/rotate-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateEgressIP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthMeResponse: {
            username: string;
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ErrorResponse: {
            error: string;
            message?: string;
        };
        OverviewResponse: {
            hub: components["schemas"]["HubInfo"];
            stats: components["schemas"]["OverviewStats"];
            /** Format: date-time */
            updated_at: string;
        };
        HubInfo: {
            public_ip: string;
            wg_ip: string;
            version: string;
            /** Format: int64 */
            uptime_seconds: number;
        };
        OverviewStats: {
            token_count: number;
            enabled_token_count: number;
            active_lease_count: number;
            egress_online_count: number;
            rotate_today_count: number;
        };
        /** @description Provisional fixed inventory and durable historical observations. No campaign activation, T0, approved release, or compliance is created. Report may passively append unknown extras; a failed batch returns projection_unavailable rather than partial healthy data. Latest classification counts span all durable members, while valid_token_count only counts currently enabled sources. */
        MigrationReadinessResponse: {
            /** @enum {integer} */
            contract_version: 2;
            inventory_registered: boolean;
            registry_id: string;
            approved_inventory_sha256: string;
            baseline_member_count: number;
            member_count: number;
            extra_member_count: number;
            /** Format: date-time */
            t0: string | null;
            observer: components["schemas"]["MigrationObserver"];
            /** @enum {boolean} */
            ready: false;
            /** @enum {string} */
            mode: "observation_only";
            /** @enum {boolean} */
            campaign_configured: false;
            observation_write_healthy: boolean;
            valid_token_count: number;
            observed_token_count: number;
            unobserved_token_count: number;
            secure_bootstrap_token_count: number;
            legacy_token_count: number;
            unknown_token_count: number;
            compat_ingress_token_count: number;
            /** Format: date-time */
            observer_started_at: string;
            /** Format: date-time */
            last_observation_at: string | null;
            blockers: components["schemas"]["MigrationBlocker"][];
            clients: components["schemas"]["MigrationClientStatus"][];
            /** Format: date-time */
            generated_at: string;
        };
        /** @description Product/version/protocol/ingress/key mode/class describe the most recent successful bootstrap; last_seen_at and history.last_seen_at also include later denied/error attempts. Installation and owner references are declarations only and never confirmed lineage. */
        MigrationClientStatus: {
            /** @enum {string} */
            membership: "baseline" | "extra" | "unregistered";
            /** @enum {string} */
            source_state: "enabled" | "disabled" | "expired" | "missing" | "invalid";
            owner_ref: string;
            shared: boolean;
            installation_refs: string[];
            /** @enum {string} */
            lineage_state: "unknown" | "declared_unverified" | "shared_unverified";
            history: components["schemas"]["MigrationHistory"];
            blockers: components["schemas"]["MigrationBlocker"][];
            token_id: string;
            observed: boolean;
            client_product: string;
            client_version: string;
            protocol_version: number;
            ingress: string;
            key_mode: string;
            private_key_returned: boolean;
            /** @enum {string} */
            migration_class: "secure_bootstrap" | "legacy" | "unknown";
            /** Format: date-time */
            last_seen_at: string | null;
        };
        /** @enum {string} */
        MigrationBlocker: "campaign_not_configured" | "inventory_not_registered" | "e2e_evidence_unavailable" | "approved_release_unavailable" | "revocation_evidence_unavailable" | "session_cleanup_unavailable" | "recovery_evidence_unavailable" | "quiet_window_unavailable" | "observer_continuity_unavailable" | "dataplane_startup_unverified" | "observation_write_failed" | "observer_gap" | "unobserved_tokens" | "non_secure_bootstrap_tokens" | "extra_unregistered" | "source_missing" | "source_disabled" | "source_expired" | "source_invalid" | "disposition_required" | "lineage_unknown" | "lineage_unverified" | "shared_lineage_unverified" | "historical_legacy" | "historical_unknown" | "historical_compat" | "historical_denied" | "historical_error";
        MigrationHistory: {
            /** Format: int64 */
            secure_bootstrap_count: number;
            /** Format: int64 */
            legacy_count: number;
            /** Format: int64 */
            unknown_count: number;
            /** Format: int64 */
            compat_ingress_count: number;
            /** Format: int64 */
            denied_count: number;
            /** Format: int64 */
            error_count: number;
            /** Format: date-time */
            first_seen_at: string | null;
            /** Format: date-time */
            last_seen_at: string | null;
        };
        MigrationObserverRun: {
            run_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            /** @enum {string} */
            state: "open" | "closed" | "failed";
            /** @enum {string} */
            reason: "none" | "write_failed" | "unclean_shutdown" | "sink_replaced" | "observer_closed";
            /** Format: date-time */
            last_success_at: string | null;
        };
        MigrationObserver: {
            current_run_id: string;
            healthy: boolean;
            gap_count: number;
            runs: components["schemas"]["MigrationObserverRun"][];
            /** Format: date-time */
            last_success_at: string | null;
        };
        TokensResponse: {
            tokens: components["schemas"]["TokenSummary"][];
        };
        TokenSummary: {
            id: string;
            masked_token: string;
            client_name: string;
            enabled: boolean;
            /** @enum {string} */
            status: "enabled" | "disabled" | "expiring" | "expired";
            egress_id: string;
            egress_name: string;
            wg_address: string;
            expires_at: string | null;
            /** Format: date-time */
            last_active_at: string | null;
        };
        TokenSecretResponse: {
            id: string;
            token: string;
        };
        LeasesResponse: {
            leases: components["schemas"]["LeaseSummary"][];
        };
        LeaseSummary: {
            token_id: string;
            masked_token: string;
            client_name: string;
            source_ip: string;
            egress_id: string;
            /** Format: date-time */
            seen_at: string;
            /** Format: date-time */
            expires_at: string | null;
        };
        EgressResponse: {
            egress: components["schemas"]["EgressSummary"][];
        };
        EgressSummary: {
            id: string;
            display_name: string;
            region: string;
            type: string;
            management_addr: string;
            proxy_addr: string;
            /** @enum {string} */
            status: "online" | "degraded" | "offline" | "deprecated";
            session_count?: number;
            active_connections?: number;
            /** Format: date-time */
            rotate_lock_until?: string | null;
            /**
             * @description Local dispatch/cooldown knowledge only. Unknown prevents redispatch in this Hub process; it does not prove remote completion or persist across restart.
             * @enum {string}
             */
            rotate_state?: "idle" | "cooldown" | "unknown";
            raw_health?: {
                [key: string]: unknown;
            } | null;
        };
        EgressExitIPResponse: {
            egress_id: string;
            exit_ip: string;
            ipv4?: string;
            ipv6?: string;
            /** Format: date-time */
            checked_at: string;
        };
        EventsResponse: {
            events: components["schemas"]["AuditEvent"][];
        };
        AuditEvent: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            occurred_at: string;
            actor: string;
            source_ip: string;
            event_type: string;
            target: string;
            detail?: {
                [key: string]: unknown;
            } | null;
            result: string;
            error_code?: string | null;
        };
        RotateIPRequest: {
            /** @default 8 */
            down_seconds: number;
        };
        RotateIPResponse: {
            /** @enum {string} */
            status: "triggered" | "busy";
            egress_id: string;
            down_seconds: number;
            retry_after_seconds?: number;
            message?: string;
        };
    };
    responses: {
        /** @description Shared expensive-request rate budget exhausted before dispatch. */
        AdmissionRateLimited: {
            headers: {
                /** @description Minimum delay in seconds before another admission attempt. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Shared expensive-request capacity unavailable or request cancelled before dispatch. */
        AdmissionUnavailable: {
            headers: {
                /** @description Present for capacity rejection; absence does not permit a mutation retry. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description JSON error response. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["AdmissionUnavailable"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current admin session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getAdminHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin service health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hub overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getMigrationReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observation-only client migration readiness report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationReadinessResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    revealTokenSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revealed token value for an authenticated admin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSecretResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listLeases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active token leases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeasesResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listEgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Egress node status list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    revealEgressExitIP: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                egress_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current public exit IP measured through the egress proxy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressExitIPResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["AdmissionRateLimited"];
            502: components["responses"]["Error"];
            503: components["responses"]["AdmissionUnavailable"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    rotateEgressIP: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                egress_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateIPRequest"];
            };
        };
        responses: {
            /** @description Rotate request dispatched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateIPResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            /** @description Egress is already rotating. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateIPResponse"];
                };
            };
            413: components["responses"]["Error"];
            429: components["responses"]["AdmissionRateLimited"];
            502: components["responses"]["Error"];
            503: components["responses"]["AdmissionUnavailable"];
        };
    };
}
