// Code generated by shared/contracts/cmd/contractgen; DO NOT EDIT.
export const CONTRACT_VERSION = 1 as const;
export const CONTROL_PROTOCOL_VERSION = 1 as const;

export interface StatusDTO {
  running: boolean;
  proxy?: string;
  proxy_reachable: boolean;
  egress?: string;
  egress_ip?: string;
  egress_ipv4?: string;
  egress_ipv6?: string;
  error?: string;
  error_code?: string;
  engine_state?: "stopped" | "starting" | "ready" | "stopping" | "degraded";
  instance_id?: string;
  config_generation?: string;
  control_protocol_version?: 1;
  port_occupied?: boolean;
  contract_version?: 1;
}

export interface ResultDTO {
  ok: boolean;
  status?: string;
  egress?: string;
  proxy?: string;
  before?: string;
  after?: string;
  message?: string;
  product?: string;
  version?: string;
  protocol_version?: number;
  error?: string;
  error_code?: string;
  contract_version?: 1;
}

export interface EngineIdentityDTO {
  instance_id: string;
  home: string;
  config_generation: string;
  control_protocol_version: 1;
  pid: number;
}
