// Code generated by shared/contracts/cmd/contractgen; DO NOT EDIT.
export const CONTRACT_VERSION = 1 as const;
export const CONTROL_PROTOCOL_VERSION = 1 as const;

export interface StatusDTO {
  running: boolean;
  proxy?: string;
  proxy_reachable: boolean;
  egress?: string;
  egress_ip?: string;
  egress_ipv4?: string;
  egress_ipv6?: string;
  error?: string;
  error_code?: string;
  engine_state?: "stopped" | "starting" | "ready" | "stopping" | "degraded";
  instance_id?: string;
  config_generation?: string;
  control_protocol_version?: 1;
  port_occupied?: boolean;
  logging_state?: "healthy" | "degraded" | "unknown";
  logging_error_code?: "engine_log_open" | "engine_log_write" | "engine_log_rotate" | "engine_log_sync" | "engine_log_namespace" | "engine_log_codec" | "engine_log_closed" | "engine_log_queue_overflow" | "engine_log_shutdown";
  contract_version?: 1;
}

export interface ResultDTO {
  ok: boolean;
  status?: string;
  egress?: string;
  proxy?: string;
  before?: string;
  after?: string;
  message?: string;
  product?: string;
  version?: string;
  protocol_version?: number;
  source_commit?: string;
  source_state?: "clean" | "dirty" | "unknown";
  go_version?: string;
  error?: string;
  error_code?: string;
  contract_version?: 1;
  system_proxy_state?: "absent" | "recorded" | "foreign" | "acquired" | "released" | "recovered";
  lease_id?: string;
  owned?: boolean;
  noop?: boolean;
  journal_path?: string;
}

export interface EngineIdentityDTO {
  instance_id: string;
  home: string;
  config_generation: string;
  control_protocol_version: 1;
  pid: number;
}
